[tool.poetry]
name = "kiwoombank"
version = "0.1.0"
description = ""
authors = ["윤철진 <zzini03182@hotmail.com>"]
readme = "README.md"
packages = [{include = "kiwoombank", from = "src"}]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = ">=0.119.0,<0.120.0"
uvicorn = ">=0.37.0,<0.38.0"
pandas = ">=2.2.0,<3.0.0"
dart-fss = "*"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
